### ISSUE TITLE
Server hang with out of memory email to cron

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#172]
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-1"
Exception in thread "main" Exception in thread "pool-1-thread-84"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-48"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-39"
java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-84"
java.lang.OutOfMemoryError: Java heap space
        at java.util.Calendar.<init>(Calendar.java:953)
        at java.util.GregorianCalendar.<init>(GregorianCalendar.java:619)
        at java.util.Calendar.createCalendar(Calendar.java:1030)
        at java.util.Calendar.getInstance(Calendar.java:968)
        at common.Log.fileDateStamp(Log.java:194)
        at common.Log.println(Log.java:164)
        at FoxTelemServer.main(FoxTelemServer.java:167)
Exception in thread "pool-1-thread-44" java.lang.OutOfMemoryError: Java heap space

In the log the last item was a Socket Exception.  That seemed to cause this.

**Comment by ac2cz** [comment]
I think this is where we get an exception in the exception handler and it spirals out of control until we run out of memory.....

**Comment by ac2cz** [comment]
Closed as duplicate
