### ISSUE TITLE
Stability issue with 1.04

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#176]
![image](https://cloud.githubusercontent.com/assets/14824793/14526585/2dfd0c2c-0212-11e6-98ed-c8332a584917.png)

**Comment by ac2cz** [comment]
20160414112635: SoundCard: threw error:
java.lang.IndexOutOfBoundsException: Attempt to read past end pointer
	at decoder.CircularByteBuffer.get(CircularByteBuffer.java:154)
	at decoder.SourceAudio.readBytes(SourceAudio.java:100)
	at decoder.SourceIQ.run(SourceIQ.java:249)
	at java.lang.Thread.run(Unknown Source)

**Comment by ac2cz** [comment]
I also saw this:
![image](https://cloud.githubusercontent.com/assets/14824793/14578366/73d91b76-0354-11e6-8ee4-fb764773345b.png)

![image](https://cloud.githubusercontent.com/assets/14824793/14578368/7a13a970-0354-11e6-867e-4a24e8072ec0.png)

20160415112658: Reading server params from: http://amsat.us/FoxTelem/server.txt
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at sun.net.www.http.KeepAliveCache$1.run(Unknown Source)
	at sun.net.www.http.KeepAliveCache$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.KeepAliveCache.put(Unknown Source)
	at sun.net.www.http.HttpClient.putInKeepAliveCache(Unknown Source)
	at sun.net.www.http.HttpClient.finished(Unknown Source)
	at sun.net.www.http.KeepAliveStream.close(Unknown Source)
	at sun.net.www.MeteredStream.justRead(Unknown Source)
	at sun.net.www.MeteredStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.read1(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at java.io.Reader.read(Unknown Source)
	at java.util.Properties$LineReader.readLine(Unknown Source)
	at java.util.Properties.load0(Unknown Source)
	at java.util.Properties.load(Unknown Source)
	at common.UpdateManager.updateServerParams(UpdateManager.java:67)
	at common.UpdateManager.run(UpdateManager.java:277)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at org.jtransforms.utils.ConcurrencyUtils.submit(ConcurrencyUtils.java:359)
	at org.jtransforms.utils.CommonUtils.cftrec4_th(CommonUtils.java:3469)
	at org.jtransforms.utils.CommonUtils.cftfsub(CommonUtils.java:443)
	at org.jtransforms.fft.DoubleFFT_1D.complexInverse(DoubleFFT_1D.java:352)
	at org.jtransforms.fft.DoubleFFT_1D.complexInverse(DoubleFFT_1D.java:307)
	at decoder.SourceIQ.inverseFFT(SourceIQ.java:443)
	at decoder.SourceIQ.processBytes(SourceIQ.java:350)
	at decoder.SourceIQ.run(SourceIQ.java:252)
	at java.lang.Thread.run(Unknown Source)

**Comment by ac2cz** [comment]
Restarted and memory usage noted as below:
![image](https://cloud.githubusercontent.com/assets/14824793/14578415/a6ee7514-0355-11e6-8c3e-22d8bcbbfec5.png)

**Comment by ac2cz** [comment]
The error "java.lang.OutOfMemoryError: Unable to create new native thread" typically means that we have run out of stack space.  Typically you can have thousands of threads, so this is a bug.  I think it is the issue where an error calls the error handler in a loop.  The issue is we do not see the original error.  I need to debug that.  We had that issue on the server recently as well.

**Comment by ac2cz** [comment]
This seems to be a rate issue.  I have not seen it again.  I am going to move it to Release 1.05 for more investigation.  Ideally we will have a mechanism for users to send crash details in to the server, so we can see how common this type of issue is.
