### ISSUE TITLE
If there are exceptions in format parsing for the web service then we crash

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#199]
Exception in thread "pool-1-thread-89" java.lang.NumberFormatException: For input string: "999999.9"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at telemServer.WebServiceProcess.run(WebServiceProcess.java:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

We need to have exception catching and error handling for ALL parse statements in the service and the server.

**Comment by ac2cz** [comment]
Closed as duplicate
