### ISSUE TITLE
The server crashes if we have too many threads and too much memory is used

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#200]
Exception in thread "pool-1-thread-12" Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2439)
        at com.mysql.jdbc.ConnectionImpl.createStatement(ConnectionImpl.java:2421)
        at telemetry.SatPayloadDbStore.insertData(SatPayloadDbStore.java:360)
        at telemetry.SatPayloadDbStore.insert(SatPayloadDbStore.java:331)
        at telemetry.SatPayloadDbStore.addRadRecord(SatPayloadDbStore.java:252)

Also:
....
lots of other errors with threads out of memory
....
Exception in thread "pool-1-thread-284" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-285" java.lang.OutOfMemoryError: Java heap space
Exception in thread "pool-1-thread-286" java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-1"

Which indicates that at LEAST 286 threads were active..

**Comment by ac2cz** [comment]
This is not because of too many threads.  Closed as duplicate of the error handling routine that consumes all the memory.
