### ISSUE TITLE
Server Crash in production, somehow tried to add image

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#234]
An ALERT file was created and the server crashed:

20160816145150: Uncaught exception.  Need to clear the ALERT and restart the server:
java.lang.NullPointerException
        at telemetry.SatPayloadDbStore.processNewImageLines(SatPayloadDbStore.java:485)
        at telemetry.PayloadDbStore.processNewImageLines(PayloadDbStore.java:943)
        at telemServer.ImageProcess.run(ImageProcess.java:21)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ac2cz** [comment]
This is because the selectImageLines() returns null and we don't check for that.
