### ISSUE TITLE
Double clicking jar file on Linux does not work at first install

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#351]
We get the welcome message, choose a folder, get the message about copying spacecraft files, then we get an error:
![image](https://user-images.githubusercontent.com/14824793/31587194-3482963a-b1ab-11e7-91b8-8b981fcae14a.png)

This is probably because we are not in the installation folder when we run it.  It runs fine if we go to the folder and run it with java -jar FoxTelem.jar.  This is an old issue.  We may not be able to fix it.

Otherwise it appears to run fine on Linux

**Comment by burnsfisher** [comment]
Hmm.  On Ubuntu I had a different behavior with FoxTelem 1.05t (the new one--just downloaded today)

Starting ./FoxTelem.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: FoxTelemMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Hmm.  Maybe I have an old set of data.  I'll see if I can tell and let you know.

**Comment by burnsfisher** [comment]
Same behavior after deleting the contents of ~/.FoxTelem
Also (and this is probably more me than you) can you make that shell script run by double clicking?  It only goes into an editor unless I go ./foxtelem in a termnial for me.

**Comment by ac2cz** [comment]
This means your version of Java needs to be updated. I realize that is not
clear. Apt-get the default jre and it will work.

I can add that to the manual. I probably won't change the release for this,
though I agree we should make the message clearer in future.

Chris

**Comment by ac2cz** [comment]
Oh, and I don't know how to make the shell script run with a double click.  I tried chmod +x and it runs from the command line but not from the GUI.

**Comment by ac2cz** [comment]
I have modified the shell script to change to the current directory and to check the Java version

**Comment by ac2cz** [comment]
I have also modified the Windows launcher to require Java 1.8, otherwise Windows users will get this same error message,

**Comment by ac2cz** [comment]
Fixed in 1.05u
