### ISSUE TITLE
If the TLE is missing then Server Crashes at startup

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#401]
This is not critical currently so the error should be more gentle.  That said, if this becomes critical then we would want to know and an exit is appropriate.

Exception in thread "main" java.lang.IllegalArgumentException: TLE line[0] was zero length
        at uk.me.g4dpz.satellite.TLE.testArguments(TLE.java:268)
        at uk.me.g4dpz.satellite.TLE.<init>(TLE.java:156)
        at uk.me.g4dpz.satellite.TLE.<init>(TLE.java:128)
        at predict.FoxTLE.<init>(FoxTLE.java:28)
        at predict.FoxTLE.importFoxSat(FoxTLE.java:65)
        at common.Spacecraft.loadTleHistory(Spacecraft.java:211)
        at common.FoxSpacecraft.<init>(FoxSpacecraft.java:102)
        at common.SatelliteManager.loadSats(SatelliteManager.java:196)
        at common.SatelliteManager.init(SatelliteManager.java:77)
        at common.SatelliteManager.<init>(SatelliteManager.java:69)
        at common.Config.basicInit(Config.java:289)
        at common.Config.serverInit(Config.java:293)
        at FoxTelemServer.main(FoxTelemServer.java:105)

**Comment by ac2cz** [comment]
This was an issue with blank lines in the TLE.  Fixed in Server v0.25
