### ISSUE TITLE
Server fills the disk with error messages if "Too Many Files Open"

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#457]
We get these messages written in a tight loop to the disk:

20180225185705: Waiting for connection ...
java.net.SocketException: Too many open files (Accept failed)
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at FoxTelemServer.main(FoxTelemServer.java:176)
20180225185705: Waiting for connection ...

**Comment by ac2cz** [comment]
This was released as server v0.30.  The code is merged into 1.06 branch too.
