### ISSUE TITLE
Server crash due to data issue

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#470]
Exception in thread "pool-1-thread-2" java.lang.ArrayIndexOutOfBoundsException: 62
        at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:454)
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2359)
        at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2779)
        at java.util.Calendar.updateTime(Calendar.java:2609)
        at java.util.Calendar.getTimeInMillis(Calendar.java:1121)
        at java.util.Calendar.getTime(Calendar.java:1094)
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1480)
        at java.text.DateFormat.parse(DateFormat.java:363)
        at telemetry.Frame.loadStp(Frame.java:476)
        at telemetry.Frame.importStpFile(Frame.java:653)
        at telemServer.ServerProcess.run(ServerProcess.java:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)

This is likely due to a bad date in the STP file.  We should catch this error and ignore it, not crash

**Comment by ac2cz** [comment]
I catch two other exceptions from this date check.  I guess depending on the Input, we may have complete nonsense that causes all sorts of random errors.  So I pull put a catch for "Exception" and set the date to null.

As an aside, this is caused by the STP date format, which is: "E, dd MMM yyyy HH:mm:ss".  This does not work well across languages.  In the FoxTelem code I try to force the language to be English for the generation of the date, but it does not seem to work in all cases.

The real fix is to change the date format to "yyyyMMddHHmmss", then it is portable.

**Comment by ac2cz** [comment]
In server v0.30
