### ISSUE TITLE
SQL Error from WebService

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#478]
20180405000843: GET /field/1/AutoSafeModeActive/conv/100/0/0 HTTP/1.0
20180405000843: Connectted to MYSQL FOXDB Version: 5.1.73-log
20180405000843:
---SQLException Caught--- Caused by: selectRows:Fox1RTTELEMETRY

20180405000843: SQLState: 42S22
20180405000843: Severity: 1054
20180405000843: Message: Unknown column 'AutoSafeModeActive' in 'field list'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'AutoSafeModeActive' in 'field list'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370)
        at telemetry.SatPayloadDbStore.getGraphData(SatPayloadDbStore.java:1019)
        at telemetry.SatPayloadDbStore.getRtGraphData(SatPayloadDbStore.java:819)
        at telemetry.PayloadDbStore.getRtGraphData(PayloadDbStore.java:639)
        at telemServer.WebHealthTab.toGraphString(WebHealthTab.java:79)
        at telemServer.WebServiceProcess.run(WebServiceProcess.java:162)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ac2cz** [comment]
Cant re-produce.  This seems to be fine
