### ISSUE TITLE
Server crash processing a date

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#500]
Exception in thread "pool-1-thread-6" java.lang.NullPointerException
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:756)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-2" java.lang.NullPointerException
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:756)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-3" java.lang.NullPointerException
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:756)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-7" java.lang.NullPointerException
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:756)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-5" java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1175)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:984)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:954)
        at java.text.DateFormat.format(DateFormat.java:344)
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:760)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-1" java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1175)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:984)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:954)
        at java.text.DateFormat.format(DateFormat.java:344)
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:760)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ac2cz** [comment]
This is in production.  Can close if we see no issues after a couple of weeks.

**Comment by ac2cz** [comment]
As a benchmark, it has been running for a few days and we still only have 4 socket files open. When we get this crash it leakes a file:

lsof | grep sock | grep java
java       25079      tlmmgr   15u     unix 0xffff88002683b0c0      0t0 576427751 socket
java       25079      tlmmgr   18u     unix 0xffff880010f8f740      0t0 576427761 socket
java       37429      tlmmgr   15u     unix 0xffff880132b94080      0t0 494731630 socket
java       37429      tlmmgr   18u     unix 0xffff880025e8b400      0t0 494731640 socket

**Comment by ac2cz** [comment]
This was seen again.  Error is below.  It is again in the importStpFile and then getPreparedInsertStmt.

Looking at what I did last time, it seems I was confused.  I removed some redundant code, but did not catch the error.  I am going to wrap the data conversion in try { } and catch anything that happens.  We have no idea what date format the user may send.  If it does not parse, we ignore it and try to carry on, using a default date/time. 

Exception in thread "pool-1-thread-8" Exception in thread "pool-1-thread-4" java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1175)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:984)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:954)
        at java.text.DateFormat.format(DateFormat.java:344)
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:760)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1175)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:984)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:954)
        at java.text.DateFormat.format(DateFormat.java:344)
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:760)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ac2cz** [comment]
Error seen today with:
AMSAT Fox Server. Version Version 0.30b - 6 Oct 2018

Exception in thread "pool-1-thread-5" Exception in thread "pool-1-thread-4" java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1175)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:984)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:954)
        at java.text.DateFormat.format(DateFormat.java:344)
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:760)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1175)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:984)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:954)
        at java.text.DateFormat.format(DateFormat.java:344)
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:760)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)

**Comment by ac2cz** [comment]
This was seen again today.  I think the challenge is that the latest server code includes a lot of changes for Husky and also has a change for PADs that can cause a crash if the layouts are wrong.  This needs to be addressed and migrated carefully.  The PADs need to be removed from the layouts in production, or rather new layouts should not be migrated and new tables are clearly not created.  The PADs are only needed in new layouts where the tables are being created - e.g. Fox-1E, Husky.

Exception in thread "pool-1-thread-5" java.lang.ArrayIndexOutOfBoundsException: -2147483648
        at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1175)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:984)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:954)
        at java.text.DateFormat.format(DateFormat.java:344)
        at telemetry.Frame.getPreparedInsertStmt(Frame.java:760)
        at telemetry.PayloadDbStore.addStpHeader(PayloadDbStore.java:479)
        at telemetry.Frame.importStpFile(Frame.java:673)
        at telemServer.ServerProcess.run(ServerProcess.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)

**Comment by ac2cz** [comment]
This was migrated to production again today. This is tracked by the branch serv_30 and is now at version 0.30c.
