### ISSUE TITLE
Crash in 1.07t when Output audio not available

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/FoxTelem#521]
Mark saw this after running for a while.  But the error in the log is for the output audio.  They may not be connected.  But its unclear what else could have caused the decoder to hang.  The Audio Graph and Eye were frozen, in addition to the missed audio.

![image](https://user-images.githubusercontent.com/14824793/48745940-5c443680-ec3b-11e8-91bc-3b9742bae0a4.png)

20181119221414: SETUP AUDIO SINK: PCM_SIGNED 48000.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 48000.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(Unknown Source)
	at com.sun.media.sound.AbstractDataLine.open(Unknown Source)
	at com.sun.media.sound.AbstractDataLine.open(Unknown Source)
	at decoder.SinkAudio.setDevice(SinkAudio.java:74)
	at decoder.Decoder.setMonitorAudio(Decoder.java:308)
	at gui.SourceTab.processStartButtonClick(SourceTab.java:1754)
	at gui.SourceTab.actionPerformed(SourceTab.java:1222)

**Comment by ac2cz** [comment]
To mitigate this I have added defensive code to confirm audioSink is not null before any writes and to catch any errors that are thrown so that the decoder is not halted.  Failure to listen to the audio (because a device is unplugged for example) should no longer halt or crash the decoder.

Fixed in 1.07u
